---
- name: "Move backend files to web server"
  become: true
  copy:
    src: /root/project/backend.tar.gz
    dest: "~/"
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: "Check for the tar file"
  become: true
  command: ls -l ~/backend.tar.gz

- name: "Unzip backend files"
  become: true
  shell: |
    tar xvzf ~/backend.tar.gz
    rm -rf ~/backend.tar.gz

- name: "start server"
  become: true
  shell: >
    pwd
    cd /backend
    npm install
    pm2 stop default
    pm2 start npm -- start