---
- name: "Move backend files to web server"
  become: true
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: "~/backend/"
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: "Check for the tar file"
  become: true
  command: ls -l ~/backend

- name: "Unzip backend files"
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz
    rm -rf artifact.tar.gz

- name: "start server"
  become: true
  shell: >
    pwd
    cd /home/ubuntu/backend
    sudo npm install
    sudo pm2 stop default
    sudo pm2 start npm -- start
