---
- name: "Move backend files to web server"
  become_user: ubuntu
  copy:
    src: /root/project/artifact.tar.gz
    dest: "~/backend"
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: "Check for the tar file"
  become_user: ubuntu
  command: ls -l ~/

- name: "Unzip backend files"
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz
    rm -rf artifact.tar.gz

- name: "start server"
  become: true
  shell: >
    pwd
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start